# Generated by Django 3.2 on 2023-04-22 06:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0002_auto_20230421_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUserTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
