# Generated by Django 3.2 on 2023-04-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0003_loginusertemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
